spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade_db
    username: postgres
    password: arjun@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092  # We'll set this up soon

server:
  port: 8080
